import { MatrixData } from "../types";

export const data: MatrixData = {
  id: 1,
  matrix_size: 5,
  matrix_name: "React Matrix",
  primary_header_title: "Consequence",
  primary_row_header_title: "Likelihood",
  matrix_description: "Risk Matrix Template",

  matrix_details: [
    {
      id: 1,
      likelihood: "E",
      consequence: 1,
      position: 5,
      matrix_type: "Risk",
      header_title: "Minor",
      header_sub_title: "Header sub-title/description.",
      row_header_title: "Rare",
      row_header_sub_title: "Row Header sub-title/description.",
    },
    {
      id: 2,
      position: 5,
      matrix_type: "Risk",
      likelihood: "D",
      consequence: 2,
      header_title: "Moderate",
      header_sub_title: "Header sub-title/description.",
      row_header_title: "Unlikely",
      row_header_sub_title: "Row Header sub-title/description.",
    },
    {
      id: 3,
      position: 5,
      matrix_type: "Risk",
      likelihood: "C",
      consequence: 3,
      header_title: "Significant",
      header_sub_title: "Header sub-title/description.",
      row_header_title: "Possible",
      row_header_sub_title: "Row Header sub-title/description.",
    },
    {
      id: 4,
      position: 5,
      matrix_type: "Risk",
      likelihood: "B",
      consequence: 4,
      header_title: "Critical",
      header_sub_title: "Header sub-title/description.",
      row_header_title: "Likely",
      row_header_sub_title: "Row Header sub-title/description.",
    },
    {
      id: 5,
      position: 5,
      matrix_type: "Risk",
      likelihood: "A",
      consequence: 5,
      header_title: "Catastrophic",
      header_sub_title: "Header sub-title/description.",
      row_header_title: "Almost Certain",
      row_header_sub_title: "Row Header sub-title/description.",
    },
  ],

  matrix_values: [
    {
      id: 26,
      matrix_id: 1,
      description: "low",
      score_value: 1,
      colour: "green",
      position: 1,
      likelihood_descriptor: "E",
      consequence_descriptor: 1,
      response: "Business as usual",
    },
    {
      id: 27,
      matrix_id: 1,
      description: "low",
      score_value: 2,
      colour: "green",
      position: 6,
      likelihood_descriptor: "D",
      consequence_descriptor: 1,
      response: "Business as usual",
    },
    {
      id: 28,
      matrix_id: 1,
      description: "low",
      score_value: 3,
      colour: "green",
      position: 2,
      likelihood_descriptor: "E",
      consequence_descriptor: 2,
      response: "Business as usual",
    },
    {
      id: 29,
      matrix_id: 1,
      description: "low",
      score_value: 4,
      colour: "green",
      position: 11,
      likelihood_descriptor: "C",
      consequence_descriptor: 1,
      response: "Business as usual",
    },
    {
      id: 30,
      matrix_id: 1,
      description: "low",
      score_value: 5,
      colour: "green",
      position: 7,
      likelihood_descriptor: "D",
      consequence_descriptor: 2,
      response: "Business as usual",
    },
    {
      id: 31,
      matrix_id: 1,
      description: "low",
      score_value: 6,
      colour: "green",
      position: 3,
      likelihood_descriptor: "E",
      consequence_descriptor: 3,
      response: "Business as usual",
    },
    {
      id: 32,
      matrix_id: 1,
      description: "medium",
      score_value: 7,
      colour: "yellow",
      position: 16,
      likelihood_descriptor: "B",
      consequence_descriptor: 1,
      response: "Requires routine to periodic monitoring",
    },
    {
      id: 33,
      matrix_id: 1,
      description: "medium",
      score_value: 8,
      colour: "yellow",
      position: 12,
      likelihood_descriptor: "C",
      consequence_descriptor: 2,
      response: "Requires routine to periodic monitoring",
    },
    {
      id: 34,
      matrix_id: 1,
      description: "medium",
      score_value: 9,
      colour: "yellow",
      position: 8,
      likelihood_descriptor: "D",
      consequence_descriptor: 3,
      response: "Requires routine to periodic monitoring",
    },
    {
      id: 35,
      matrix_id: 1,
      description: "medium",
      score_value: 10,
      colour: "yellow",
      position: 4,
      likelihood_descriptor: "E",
      consequence_descriptor: 4,
      response: "Requires routine to periodic monitoring",
    },
    {
      id: 36,
      matrix_id: 1,
      description: "medium",
      score_value: 11,
      colour: "yellow",
      position: 21,
      likelihood_descriptor: "A",
      consequence_descriptor: 1,
      response: "Requires routine to periodic monitoring",
    },
    {
      id: 37,
      matrix_id: 1,
      description: "high",
      score_value: 12,
      colour: "orange",
      position: 17,
      likelihood_descriptor: "B",
      consequence_descriptor: 2,
      response: "Risk requires targeted management plan",
    },
    {
      id: 38,
      matrix_id: 1,
      description: "high",
      score_value: 13,
      colour: "orange",
      position: 13,
      likelihood_descriptor: "C",
      consequence_descriptor: 3,
      response: "Risk requires targeted management plan",
    },
    {
      id: 39,
      matrix_id: 1,
      description: "high",
      score_value: 14,
      colour: "orange",
      position: 9,
      likelihood_descriptor: "D",
      consequence_descriptor: 4,
      response: "Risk requires targeted management plan",
    },
    {
      id: 40,
      matrix_id: 1,
      description: "high",
      score_value: 15,
      colour: "orange",
      position: 5,
      likelihood_descriptor: "E",
      consequence_descriptor: 5,
      response: "Risk requires targeted management plan",
    },
    {
      id: 41,
      matrix_id: 1,
      description: "high",
      score_value: 16,
      colour: "orange",
      position: 22,
      likelihood_descriptor: "A",
      consequence_descriptor: 2,
      response: "Risk requires targeted management plan",
    },
    {
      id: 42,
      matrix_id: 1,
      description: "high",
      score_value: 17,
      colour: "orange",
      position: 18,
      likelihood_descriptor: "B",
      consequence_descriptor: 3,
      response: "Risk requires targeted management plan",
    },
    {
      id: 43,
      matrix_id: 1,
      description: "high",
      score_value: 18,
      colour: "orange",
      position: 14,
      likelihood_descriptor: "C",
      consequence_descriptor: 4,
      response: "Risk requires targeted management plan",
    },
    {
      id: 44,
      matrix_id: 1,
      description: "high",
      score_value: 19,
      colour: "orange",
      position: 10,
      likelihood_descriptor: "D",
      consequence_descriptor: 5,
      response: "Risk requires targeted management plan",
    },
    {
      id: 45,
      matrix_id: 1,
      description: "extreme",
      score_value: 20,
      colour: "red",
      position: 23,
      likelihood_descriptor: "A",
      consequence_descriptor: 3,
      response: "Activity should not commence",
    },
    {
      id: 46,
      matrix_id: 1,
      description: "extreme",
      score_value: 21,
      colour: "red",
      position: 19,
      likelihood_descriptor: "B",
      consequence_descriptor: 4,
      response: "Activity should not commence",
    },
    {
      id: 47,
      matrix_id: 1,
      description: "extreme",
      score_value: 22,
      colour: "red",
      position: 15,
      likelihood_descriptor: "C",
      consequence_descriptor: 5,
      response: "Activity should not commence",
    },
    {
      id: 48,
      matrix_id: 1,
      description: "extreme",
      score_value: 23,
      colour: "red",
      position: 24,
      likelihood_descriptor: "A",
      consequence_descriptor: 4,
      response: "Activity should not commence",
    },
    {
      id: 49,
      matrix_id: 1,
      description: "extreme",
      score_value: 24,
      colour: "red",
      position: 20,
      likelihood_descriptor: "B",
      consequence_descriptor: 5,
      response: "Activity should not commence",
    },
    {
      id: 50,
      matrix_id: 1,
      description: "extreme",
      score_value: 25,
      colour: "red",
      position: 25,
      likelihood_descriptor: "A",
      consequence_descriptor: 5,
      response: "Activity should not commence",
    },
  ],
};
